name: choco_gpu
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.0=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiosignal==1.3.1
      - altair==5.4.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.13.1
      - appdirs==1.4.4
      - asttokens==2.4.1
      - attrs==24.2.0
      - autograd==1.6.2
      - autoray==0.6.12
      - blinker==1.9.0
      - cachetools==5.4.0
      - certifi==2024.7.4
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.2.1
      - cryptography==43.0.0
      - cuquantum==24.3.0.post1
      - cuquantum-cu12==24.3.0.post1
      - custatevec-cu12==1.6.0.post1
      - cutensor-cu12==2.0.2
      - cutensornet-cu12==2.4.0.post1
      - cycler==0.12.1
      - Cython==3.0.10
      - debugpy==1.8.2
      - decorator==5.1.1
      - dill==0.3.8
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - filelock==3.15.4
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - future==1.0.0
      - gitdb==4.0.11
      - GitPython==3.1.43
      - gurobipy==11.0.3
      - ibm-cloud-sdk-core==3.20.3
      - ibm-platform-services==0.55.1
      - idna==3.7
      - ipykernel==6.29.5
      - ipython==8.26.0
      - jax==0.4.34
      - jaxlib==0.4.34
      - jedi==0.19.1
      - Jinja2==3.1.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter_client==8.6.2
      - jupyter_core==5.7.2
      - kiwisolver==1.4.5
      - markdown-it-py==3.0.0
      - MarkupSafe==2.1.5
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml_dtypes==0.5.0
      - mpmath==1.3.0
      - mqt.ddsim==1.22.0
      - msgpack==1.1.0
      - mthree==2.6.3
      - narwhals==1.13.3
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numpy==2.1.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - openqasm3==0.5.0
      - opt_einsum==3.4.0
      - orjson==3.10.6
      - packaging==24.1
      - pandas==2.2.2
      - parso==0.8.4
      - pbr==6.0.0
      - PennyLane==0.35.0
      - PennyLane-qiskit==0.31.0
      - PennyLane_Lightning==0.36.0
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.2.2
      - prompt_toolkit==3.0.47
      - protobuf==5.28.2
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure_eval==0.2.3
      - pyarrow==18.0.0
      - pycparser==2.22
      - pydantic==2.8.2
      - pydantic_core==2.20.1
      - pydeck==0.9.1
      - Pygments==2.18.0
      - PyJWT==2.8.0
      - pyparsing==3.1.2
      - PySocks==1.7.1
      - pyspnego==0.11.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - PyYAML==6.0.2
      - pyzmq==26.0.3
      - qiskit==1.2.4
      - qiskit-aer-gpu==0.15.1
      - qiskit-ibm-provider==0.11.0
      - qiskit-ibm-runtime==0.25.0
      - qiskit-qasm3-import==0.5.0
      - ray==2.37.0
      - referencing==0.35.1
      - requests==2.32.3
      - requests_ntlm==1.3.0
      - rich==13.9.4
      - rpds-py==0.20.0
      - rustworkx==0.15.1
      - scipy==1.14.0
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - six==1.16.0
      - smmap==5.0.1
      - socks==0
      - stack-data==0.6.3
      - stevedore==5.2.0
      - streamlit==1.40.0
      - symengine==0.11.0
      - sympy==1.13.1
      - tenacity==9.0.0
      - toml==0.10.2
      - torch==2.4.0
      - torchaudio==2.4.0
      - torchvision==0.19.0
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - triton==3.0.0
      - typing_extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - watchdog==5.0.3
      - wcwidth==0.2.13
      - websocket-client==1.8.0
      - websockets==12.0